### ISSUE TITLE
Add option to ignore files/folders

### ISSUE THREAD

**Issue by jkevingutierrez** [dizballanze/gray#11]
Similar to the `--exclude` option in [black](https://github.com/psf/black#configuration) or [autoflake](https://github.com/myint/autoflake#advanced-usage) it would be good to have an option to exclude files and folders

**Comment by sodul** [comment]
@dizballanze since this will help me with a more complex issue, I will take a stab at it.

**Comment by sodul** [comment]
@dizballanze, gentle ping. I've posted a few PRs, including one that will address this. That will allow us to then more easily managed a couple of subdirectories in our mono repo that need to maintain backward compatibility with older versions of python.

**Comment by dizballanze** [comment]
Hi, @sodul.
I am going to check this out on this weekends.

**Comment by dizballanze** [comment]
Hi, @sodul !
All your PRs are merged and released here https://pypi.org/project/gray/0.11.0/

**Comment by sodul** [comment]
Thanks @dizballanze, with the prior PRs in place I was able to add my exclusion changes. The PR is ready for review at your convenience.
