### ISSUE TITLE
Add Blue as an alternative to Black

### ISSUE THREAD

**Issue by sodul** [dizballanze/gray#25]
We use `gray` with `black` and `unify` so that we can get the formatting from Black yet use single quotes. Since Blue is a more direct solution to use single quotes (it patches Black to do so), I was thinking that Blue could be added.

Since I did the work to add Black in v0.10.0 I should be able to submit a PR for this as well.

https://github.com/grantjenks/blue

**Comment by dizballanze** [comment]
Hey
Sure, feel free to add `blue` as an optional dependency.

**Comment by sodul** [comment]
I took a deeper look at Blue and it is pinning `black==22.1.0` which is undesirable as it would cause issues with Python 3.12. Blue itself would require some changes and a new release and has not been updated in 2 years so I do not feel that this is viable unfortunately.

Closing.
