### ISSUE TITLE
Add support for Black

### ISSUE THREAD

**Issue by sodul** [dizballanze/gray#8]
I understand the idea is a bit counter to what gray intents to offer but we think this can make sense.

We use the following to format our code:
- pyupgrade 
- black -S -l 100
- isort (with google profile)
- unify

We have now added all of this as part of our CI pipeline and have a small script wrapping all that.
If we were to use gray, it would be able to handle all of this in a more straightforward manner and have better pre-commit support.

We settled on using Black as it turns out to be both pretty fast and quite compatible with modern python syntax, working on code where yapf would simply crash for example. The consistency of the formatted code is good as it removes the distraction of the formatting from PR reviews.

Since each formatter is optional in Gray, I think supporting black is actually natural. And black is just a very dark shade of gray, right?

If you are open to the idea I can look into submitting a PR.

**Comment by dizballanze** [comment]
Hi!
I'm ok with that. But I think black should be disabled by default.

**Comment by sodul** [comment]
Definitely, the idea is to add that as an option so we have a single command to reformat python code.
